
// ── Transition Engine Types ──────────────────────────────────────────────────
export type TransitionStyle =
  | 'PHRASES_CROSSFADE'
  | 'EQ_SWAP'
  | 'FILTER_SWEEP'
  | 'ECHO_OUT'
  | 'LOOP_ROLL'
  | 'BACKSPIN'
  | 'REVERB_WASH'
  | 'BRAKE_STOP'
  | 'SLAM'
  | 'GATER'
  | 'DOUBLE_DROP';

export interface TransitionAnalysis {
  bpmDelta: number;        // Absolute BPM difference
  camelotScore: number;    // 0-1 harmonic compatibility
  genreMatch: boolean;     // Same genre family?
  energyDelta: number;     // trackB.energy - trackA.energy
  hasVocalsA: boolean;     // Track A likely has prominent vocals
  hasVocalsB: boolean;     // Track B likely has prominent vocals
  structureKnown: boolean; // Do we have beatgrid/structure data?
  rmsRatioDb: number;      // Loudness difference in dB (for gain matching)
}

export interface Track {
  id: string;
  file: File;
  name: string;
  duration: number; // in seconds
  bpm: number;
  detectedBpm?: number; // DSP analyzed BPM
  key?: string; // Camelot Key
  buffer?: AudioBuffer;
  status: 'queued' | 'loading' | 'analyzing' | 'ready' | 'playing' | 'played' | 'error';
  vibe?: {
    description: string;
    texture: string;
    mood: string;
  };
  energyLevel?: number; // 1-10 predicted by Gemini
  genre?: string;
  bestTransitionTip?: string; // Generated by Gemini
  loudnessRating?: number;
  gainCorrection?: number;
  spectralCharacteristics?: { low: number, mid: number, high: number };
  structure?: {
    musicStartTime: number; // For skipping silent intros
    introEndTime: number;
    drops: number[]; // Array of timestamps
    breakdowns: number[]; // Array of timestamps
    outroStartTime: number;
    hasDrop: boolean;
  };
  stemBuffers?: {
    vocals: AudioBuffer;
    drums: AudioBuffer;
    bass: AudioBuffer;
    other: AudioBuffer;
  };
  stemsReady?: boolean;
  stemsSeparating?: boolean;
  embedding?: number[]; // [NEW] High-dimensional Vibe Embedding
  artistEmbedding?: number[]; // [NEW] Artist Similarity Embedding
}

export enum DJMode {
  MANUAL = 'MANUAL',
  AUTO = 'AUTO',
  PLAYLIST = 'PLAYLIST',
}

export type MasterFxType = 'NONE' | 'REVERB' | 'DELAY' | 'FLANGER' | 'PHASER';



export interface FXSlot {
  name: string;
  amount: number;
  active: boolean;
}

export interface DeckSpecificState {
  isSyncEnabled: boolean;
  isLooping: boolean;
  loopLength: number;
  cuePoint: number;
  gain: number;
  eq: {
    low: number;
    mid: number;
    high: number;
  };
  fx: FXSlot[];
  filter: number;
}

export interface MasterState {
  isRecording: boolean;
  recordingTime: number;
  crowdVolume: number;
  aiHostEnabled: boolean;
  limiterReduction: number;
  mode: DJMode;
  crossfader: number;
  masterFxType: MasterFxType;
  masterFxWet: number;
}
